version: "3"

services:
  redis:
    container_name: redis_prod
    image: redis
    command: "--appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - ./server/redis/redis_data:/data
      - ./server/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
  server:
    image: isnob46/remote_backup_server:latest
    container_name: remote_backup_server
    volumes:
      - ./server/data:/data
    expose:
      - "5555"
    ports:
      - "5555:5555"
    depends_on:
      - redis
    command: bash -c -s "./src/server"
