version: "3"
services:
  server:
    build: .
    image: remote_backup_server
    container_name: remote_backup_server_full
    ports:
      - "4444:4444"
    volumes:
      - ./remote_backup_server/src:/remote_backup_server/src
    working_dir: /remote_backup_server/src
    command: bash -c -s "ls && cmake . && make && ./remote_backup_server"
  client:
    build: .
    image: remote_backup_client
    container_name: remote_backup_client_full
    ports:
      - "5555:4444"
    volumes:
      - ./remote_backup_client/src:/remote_backup_client/src
      - ./remote_backup_client/my_sync_folder:/remote_backup_client/my_sync_folder
    working_dir: /remote_backup_client/src
    command: bash -c -s "ls && cmake . && make && ./remote_backup_client"
