redis:
  container_name: redis
  image: redis
  command: "--appendonly yes"
  ports:
    - "6379:6379"
  volumes:
    - ./redis_data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
  restart: always
