version: "3"
services:
  client:
    build: .

    image: remote_backup_client
    container_name: remote_backup_client
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - ./my_sync_folder  :/remote_backup_client/my_sync_folder
    working_dir: /remote_backup_client/
    #command: bash -c -s "cp -r ./src ./build && cd build &&  ls && cmake . && make"
    command: ./remote_backup_client
